name: Release app

on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Npm install
        run: npm ci

      - name: Generate dict
        run: npm run build

      - name: Generate release
        run: npm run neu-release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/rotate-release.zip
            dist/rotate/resources.neu
