name: Release app

on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Npm install
        run: npm ci

      - name: Sync versions
        run: npm run sync-version

      - name: Generate dict
        run: npm run build

      - name: Generate release
        run: npm run neu-release

      - name: Generate build
        run: npm run neu-build

      - name: Copy build
        run: Copy-Item -Path .\dist\rotate\resources.neu -Destination ~\resources.neu

      - name: Add icon to win exe
        run: |
          Expand-Archive -Path .\dist\rotate-release.zip -DestinationPath .\release
          .\rcedit-x64.exe .\release\rotate-win_x64.exe --set-icon .\public\favicon.ico
          Compress-Archive -Path .\release -DestinationPath .\dist\rotate-release.zip -Force

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .\dist\rotate-release.zip

      - uses: actions/checkout@v2
      - name: Commit release
        run: |
          git config --global user.name 'Yauhen Pyl'
          git config --global user.email 'yauhen.pyl@gmail.com'
          git fetch
          git checkout master
          npm run sync-version
          npm ci
          Copy-Item -Path ~/resources.neu -Destination ./resources.neu
          git commit -am "Automated release"
          git push
